# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 15:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='your location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_distance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Distance', verbose_name='find me players within this distance (miles)'),
        ),
    ]
