# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20171015_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known', models.BooleanField(default=False)),
                ('found_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_found', to='accounts.UserInstrument')),
                ('found_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_found', to=settings.AUTH_USER_MODEL)),
                ('requesting_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_looked_for', to='accounts.UserInstrument')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_looked_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
