# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171114_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
