# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
