# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='received_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
