# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20171123_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invited_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instrument'),
        ),
    ]
