# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_auto_20171125_0125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set([('invited_user', 'group')]),
        ),
    ]
