# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20171129_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
